#!/usr/bin/bash

######################
# Configuration part #
######################

# String passed to "ls" with the path for the log files
LOGSPATH="/var/apache2/2.2/logs/access_log.*"

########################
# End of configuration #
########################

for FILE in $(ls ${LOGSPATH})
do
	DATE="$(echo ${FILE} | awk -F. '{print $3}')"
	echo -n "${DATE}: "
	echo "${FILE}" | grep -q ".gz$"
	if [ ${?} -eq 0 ]
	then
		# A gzipped file
		gzcat ${FILE} | awk '{total += $10} END {total = total/1024/1024/1024; printf "%.2f GB\n", total}'
	else
		# An uncompressed file
		awk '{total += $10} END {total = total/1024/1024/1024; printf "%.2f GB\n", total}' ${FILE}
	fi
done
